services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRESDB_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_DB: ${POSTGRESDB_DATABASE}
    ports:
      - 5432:5432
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 13000:3000